server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /.well-known/acme-challenge/ {
        # Let's encrypt webroot certificate obtaining method
        root /var/www/federation_registry_frontend/;
    }
    location / {
        # Redirect all HTTP requests to HTTPS
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name _;

    ssl_certificate /etc/ssl/certs/federation-registry-cert.pem;
    ssl_certificate_key /etc/ssl/private/federation-registry-key.pem;

    root /var/www/federation_registry_frontend/;

    location / {
        try_files $uri /index.html;
#        gzip_types application/javascript text/css image/svg+xml;
#        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
        location = / {
            return 302 /cesnet/home; # temporary redirect (302) to allow hostname reuse. cesnet = your tenant name
        }
#        location = /index.html {
#            gzip_static on;
#        }
    }

    location /static/ {
        gzip_static on;
#        expires 7d;
    }

    location /img/ {
        gzip_static on;
#        expires 7d;
    }

    location = /ams_verification_hash {
  	    return 302 /federation-backend/ams/ams_verification_hash;
    }

    location = /federation-backend {
        return 301 /federation-backend/;
    }

    location /federation-backend/ {
        rewrite ^/federation-backend/(.*) /$1 break;
        proxy_pass http://rciam-backend-api;
        gzip_types application/json;
        # Do not allow X-Api-Key usage for proxied requests, API clients connect directly to the backend-api, not via NGINX
        proxy_set_header X-Api-Key "";
    }
}

upstream rciam-backend-api {
    keepalive 3;
    server [fd77:fed:bac::80]:5000;
}