---
# handlers file for cesnet.rciam_registry
- name: Reload NGINX in frontend
  community.docker.docker_compose_v2_exec:
    service: frontend
    command: nginx -s reload
    project_src: "{{ federation_registry_config_path }}"
  when: not docker_compose_status | community.general.json_query('actions[?status==`Recreate`].id | contains(@, `rciam-registry_frontend`)')

- name: Restart backend-api
  community.docker.docker_compose_v2:
    services: backend-api
    state: restarted
    project_src: "{{ federation_registry_config_path }}"
  when: not docker_compose_status | community.general.json_query('actions[?status==`Recreate`].id | contains(@, `rciam-registry_backend-api`)')

- name: Restart deployers
  community.docker.docker_compose_v2:
    services: "deployer-{{ item.name }}"
    state: restarted
    project_src: "{{ federation_registry_config_path }}"
  with_list: "{{ federation_registry_deployers }}"
  # contains() on array is exact match, and no partial match is available. For now, match only the first container ID.
  # Manual restart of the second container will be required, in case that first container has been restarted by docker-compose, but config has been updated for the second.
  when: not docker_compose_status | community.general.json_query('actions[?status==`Recreate`].id | contains(@, `rciam-registry_deployer-' + federation_registry_deployers[0].name + '`)')

- name: Restart rabbitmq
  community.docker.docker_compose_v2:
    services: rabbitmq
    state: restarted
    project_src: "{{ federation_registry_config_path }}"
  when: not docker_compose_status | community.general.json_query('actions[?status==`Recreate`].id | contains(@, `rciam-registry_rabbitmq`)')

- name: Restart rabbitmq-agents
  community.docker.docker_compose_v2:
    services: "rabbitmq-agent-{{ item.name }}"
    state: restarted
    project_src: "{{ federation_registry_config_path }}"
  with_list: "{{ federation_registry_rabbitmq_agents }}"
  # contains() on array is exact match, and no partial match is available. For now, match only the first container ID.
  # Manual restart of the second container will be required, in case that first container has been restarted by docker-compose, but config has been updated for the second
  when: not docker_compose_status | community.general.json_query('actions[?status==`Recreate`].id | contains(@, `rciam-registry_rabbitmq-agent-' + federation_registry_rabbitmq_agents[0].name + '`)')